[package]
name        = "org.openssl.openssl-debuginfo"
description = "OpenSSL debugging symbols"

[dependencies]
"org.openssl.libcrypto" = "{{version}}-2"
"org.openssl.libssl"    = "{{version}}-2"
"org.openssl.openssl"   = "{{version}}-2"

[files]
"@source:LICENSE.txt" = "usr/share/licenses/org.openssl.openssl-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
