[package]
name        = "org.openssl.openssl-debuginfo"
description = "OpenSSL debugging symbols"

[dependencies]
"org.openssl.libcrypto" = "= {{release}}"
"org.openssl.libssl"    = "= {{release}}"
"org.openssl.openssl"   = "= {{release}}"

[files]
"@source:LICENSE.txt" = "usr/share/licenses/org.openssl.openssl-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
