[package]
name        = "org.openssl.openssl-debugsource"
description = "OpenSSL debug sources"

[dependencies]
"org.openssl.openssl-debuginfo" = "= {{release}}"

[files]
"@source:LICENSE.txt" = "usr/share/licenses/org.openssl.openssl-debugsource/"
":usr/src/debug/**" = "usr/src/debug"
