[package]
name        = "org.openssl.libssl"
description = "OpenSSL TLS runtime library"

[provides]
libssl = "{{version}}"

[dependencies]
glibc                   = ">= 2.43"
"org.openssl.libcrypto" = "{{version}}-1"

[files]
"@source:LICENSE.txt"                        = "usr/share/licenses/org.openssl.libssl/"
":usr/lib/x86_64-linux-peios/libssl.so.3"    = "usr/lib/x86_64-linux-peios/libssl.so.3"
