[package]
name        = "org.gnu.which-debugsource"
description = "GNU which debug sources"

[dependencies]
"org.gnu.which-debuginfo" = "{{version}}-1"

[files]
"@source:COPYING" = "usr/share/licenses/org.gnu.which-debugsource/COPYING"
":usr/src/debug/**" = "usr/src/debug"
