[package]
name = "nl.bitwizard.mtr-debugsource"
description = "Debug sources"
[dependencies]
"nl.bitwizard.mtr-debuginfo" = "= {{release}}"
[files]
"@source:COPYING" = "usr/share/licenses/nl.bitwizard.mtr-debugsource/COPYING"
":usr/src/debug/**" = "usr/src/debug"
