[package]
name        = "io.github.zlib-ng.zlib-ng-static"
description = "zlib-ng native API static SDK umbrella"
license     = "Zlib"

[provides]

[replaces]

[dependencies]
"io.github.zlib-ng.zlib-ng-devel" = "= {{release}}"

[files]
"@source:LICENSE.md"                           = "usr/share/licenses/io.github.zlib-ng.zlib-ng-static/"
