# Shared metadata for the zlib-ng source family.  Binary members narrow this
# source-wide expression to Zlib; the additional terms cover test vectors that
# are redistributed only in the generated corresponding-source package.

format = "peipkg"

[package]
version       = "{{version}}-2"
architecture  = "x86_64"
license       = "Zlib AND CC-BY-3.0 AND CC-BY-4.0 AND LicenseRef-Public-Domain"
license_class = "free"
homepage      = "https://github.com/zlib-ng/zlib-ng"
