#!/bin/python3
"""Fail-closed installed-Clang pointer-offset regression; no host headers or linking."""
import argparse, hashlib, json, pathlib, subprocess, sys

SIZES=(255,256,257,511,512,513,65535,65536,65537)
POSITIVE={
 'prefix_increment_start': 'int *p=a; int *q=++p; return p==a+1 && q==a+1;',
 'postfix_increment_start': 'int *p=a; int *q=p++; return p==a+1 && q==a;',
 'prefix_increment_end': 'int *p=a+N-1; int *q=++p; return p==a+N && q==a+N;',
 'postfix_increment_end': 'int *p=a+N-1; int *q=p++; return p==a+N && q==a+N-1;',
 'prefix_decrement_end': 'int *p=a+N; int *q=--p; return p==a+N-1 && q==a+N-1;',
 'postfix_decrement_end': 'int *p=a+N; int *q=p--; return p==a+N-1 && q==a+N;',
 'prefix_decrement_start': 'int *p=a+1; int *q=--p; return p==a && q==a;',
 'postfix_decrement_start': 'int *p=a+1; int *q=p--; return p==a && q==a+1;',
 'cross_255': 'int *p=a+254; ++p; if(p!=a+255)return false; --p; return p==a+254;',
 'unsigned_add_subtract': 'unsigned long long n=N; int *p=a; p+=n; if(p!=a+N)return false; p-=n; return p==a;',
 'signed_add_subtract': 'long long n=N; int *p=a; p+=n; if(p!=a+N)return false; p-=n; return p==a;',
 'negative_add_subtract': 'long long n=-N; int *p=a+N; p+=n; if(p!=a)return false; p-=n; return p==a+N;',
 'zero_at_one_past': 'int *p=a+N; p+=0u; p-=0ll; return p==a+N;',
 'subscript_boundaries': 'a[0]=17; a[N-1]=23; int *p=a+N; --p; return *p==23 && *(p-(N-1u))==17;',
}
NEGATIVE={
 'prefix_increment_past_end': ('int *p=a+N;', '++p;', lambda n:n+1),
 'postfix_increment_past_end': ('int *p=a+N;', 'p++;', lambda n:n+1),
 'prefix_decrement_before_start': ('int *p=a;', '--p;', lambda n:-1),
 'postfix_decrement_before_start': ('int *p=a;', 'p--;', lambda n:-1),
 'unsigned_add_past_end': ('int *p=a+N;', 'p+=1ull;', lambda n:n+1),
 'unsigned_subtract_before_start': ('int *p=a;', 'p-=1ull;', lambda n:-1),
 'negative_add_before_start': ('int *p=a;', 'p+=-1ll;', lambda n:-1),
 'negative_subtract_past_end': ('int *p=a+N;', 'p-=-1ll;', lambda n:n+1),
 'wide_signed_add': ('int *p=a; __int128 off=static_cast<__int128>(1)<<80;', 'p+=off;', lambda n:1<<80),
 'wide_signed_negative_add': ('int *p=a+N; __int128 off=static_cast<__int128>(1)<<80;', 'p+=-off;', lambda n:n-(1<<80)),
 'wide_signed_subtract': ('int *p=a+N; __int128 off=static_cast<__int128>(1)<<80;', 'p-=off;', lambda n:n-(1<<80)),
 'wide_signed_negative_subtract': ('int *p=a; __int128 off=static_cast<__int128>(1)<<80;', 'p-=-off;', lambda n:1<<80),
 'wide_unsigned_add': ('int *p=a; unsigned __int128 off=static_cast<unsigned __int128>(1)<<80;', 'p+=off;', lambda n:1<<80),
 'wide_unsigned_subtract': ('int *p=a+N; unsigned __int128 off=static_cast<unsigned __int128>(1)<<80;', 'p-=off;', lambda n:n-(1<<80)),
}

def fixture(n,negative):
 lines=['// Generated by run.py; standalone C++17, no external headers.',f'constexpr int N={n};']
 if not negative:
  lines+=['// expected-no-diagnostics']
  for name,body in POSITIVE.items():
   lines += [f'constexpr bool {name}() {{ int a[N]={{}}; {body} }}',f'static_assert({name}(), "{name}");']
 else:
  for name,(setup,op,index) in NEGATIVE.items():
   # The inactive branch is valid, so the diagnostic must be at the actual invalid operation.
   lines += [f'constexpr int {name}(bool active) {{', '  if(!active)return 0;',f'  int a[N]={{}}; {setup}',
    f'  {op} // expected-note {{{{cannot refer to element {index(n)} of array of {n} elements in a constant expression}}}}',
    '  return 0;', '}',
    f'constexpr int result_{name}={name}(true); // expected-error {{{{constexpr variable \'result_{name}\' must be initialized by a constant expression}}}} expected-note {{{{in call to \'{name}(true)\'}}}}']
 return '\n'.join(lines)+'\n'

def main():
 ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--clang',required=True);ap.add_argument('--output',required=True);ap.add_argument('--label',default='installed-compiler diagnostic');a=ap.parse_args()
 clang=pathlib.Path(a.clang).resolve();out=pathlib.Path(a.output).resolve();out.mkdir(parents=True,exist_ok=False)
 sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
 result={'scope':a.label,'compiler':str(clang),'compiler_sha256':sha(clang),'runner_sha256':sha(pathlib.Path(__file__)),'sizes':SIZES,'positive_cases_per_size':len(POSITIVE),'negative_cases_per_size':len(NEGATIVE),'cases':[]}
 for n in SIZES:
  for negative in (False,True):
   kind='bounds-diagnostics' if negative else 'valid-operations';source=out/f'{n}-{kind}.cpp';source.write_text(fixture(n,negative))
   for mode in ('default','experimental'):
    cmd=[str(clang),'-cc1','-std=c++17','-fsyntax-only','-ferror-limit','0','-verify',str(source)]
    if mode=='experimental':cmd+=['-fexperimental-new-constant-interpreter']
    log=out/f'{n}-{kind}-{mode}.log'
    with log.open('w') as stream:
     run=subprocess.run(cmd,stdout=stream,stderr=subprocess.STDOUT,timeout=60)
    result['cases'].append({'size':n,'kind':kind,'mode':mode,'command':cmd,'returncode':run.returncode,'source_sha256':sha(source),'log':str(log),'log_sha256':sha(log),'checks':len(NEGATIVE if negative else POSITIVE)})
 result['passed']=sum(c['returncode']==0 for c in result['cases']);result['failed']=len(result['cases'])-result['passed'];result['complete']=True
 (out/'result.json').write_text(json.dumps(result,indent=2)+'\n')
 print(json.dumps({k:result[k] for k in ('passed','failed','complete')}))
 return bool(result['failed'])
if __name__=='__main__':sys.exit(main())
