[package]
name        = "org.kernel.libcap-debuginfo"
description = "Linux POSIX capabilities debugging symbols"

[dependencies]
"org.kernel.libcap"       = "{{version}}-1"
"org.kernel.libcap-tools" = "{{version}}-1"

[files]
"@source:License"   = "usr/share/licenses/org.kernel.libcap-debuginfo/License"
":usr/lib/debug/**" = "usr/lib/debug"
