[package]
name = "org.openssl.openssl3-debugsource"
description = "OpenSSL 3 compatibility debugsource"

[dependencies]
"org.openssl.openssl3-debuginfo" = "= {{release}}"

[files]
"@source:LICENSE.txt" = "usr/share/licenses/org.openssl.openssl3-debugsource/"
":usr/src/debug/**" = "usr/src/debug"
