[package]
name        = "org.gnu.findutils-debuginfo"
description = "GNU Findutils debugging symbols"

[dependencies]
"org.gnu.findutils" = "{{version}}-1"

[files]
"@source:COPYING*"  = "usr/share/licenses/org.gnu.findutils-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
