[package]
name        = "org.gnu.bc-debugsource"
description = "GNU bc and dc debug sources"

[dependencies]
"org.gnu.bc-debuginfo" = "{{version}}-2"

[files]
"@source:COPYING*"   = "usr/share/licenses/org.gnu.bc-debugsource/"
":usr/src/debug/**" = "usr/src/debug"
