[package]
name        = "com.darwinsys.file-debuginfo"
description = "file and libmagic - debugging symbols"

[dependencies]
"com.darwinsys.file"          = "= {{release}}"
"com.darwinsys.file-libmagic" = "= {{release}}"

[files]
"@source:COPYING"   = "usr/share/licenses/com.darwinsys.file-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
