[package]
name        = "org.gnu.coreutils-debugsource"
description = "GNU core utilities - debug sources"

[dependencies]
"org.gnu.coreutils-debuginfo" = "{{version}}-1"

[files]
"@source:COPYING*" = "usr/share/licenses/org.gnu.coreutils-debugsource/"
":usr/src/debug/**" = "usr/src/debug"
