"""Generate a deterministic command reference from the actual staged Ninja."""
from pathlib import Path
import gzip, os, re, subprocess, sys
binary, output = sys.argv[1:]
env = dict(os.environ, LC_ALL="C")
result = subprocess.run([binary, "--help"], capture_output=True, text=True, env=env)
if result.returncode != 1 or not result.stderr.startswith("usage: ninja "):
    raise SystemExit("unexpected Ninja help interface")
help_text = re.sub(r"\[default=\d+ on this system\]", "[default=automatic for this system]", result.stderr)
version = subprocess.check_output([binary, "--version"], text=True, env=env).strip()
if not re.fullmatch(r"[0-9]+(?:\.[0-9]+)+", version):
    raise SystemExit("unexpected Ninja version")

def roff(text):
    return "\n".join("\\&" + line.replace("\\", "\\e").replace("-", "\\-") for line in text.splitlines())

page = f''' .TH NINJA 1 "" "Ninja {version}" "User Commands"
.SH NAME
ninja \\- execute a dependency graph of build commands
.SH SYNOPSIS
.B ninja
.RI [ options ] " " [ targets ... ]
.SH DESCRIPTION
Ninja reads a build graph, normally from build.ninja, and executes the commands
needed to update the requested targets. With no target argument it selects the
default targets from that graph. Build files are usually generated by a higher
level build system.
.SH OPTIONS
The following reference is obtained from the packaged executable.
.nf
{roff(help_text)}
.fi
.SH TOOLS
Run ninja -t list to list the tools supplied by this version. Tool arguments
follow the tool name. Tools inspect the graph, list commands, clean generated
outputs, and perform other build maintenance operations.
.SH FILES
.TP
.I build.ninja
Build graph read unless overridden by the -f option.
.TP
.I .ninja_log
Command timing and incremental build log.
.TP
.I .ninja_deps
Discovered dependency database.
.SH SEE ALSO
The complete Ninja language and user manual is installed at
/usr/share/doc/org.ninja-build.ninja/manual.asciidoc.
'''.lstrip()
path = Path(output)
path.parent.mkdir(parents=True, exist_ok=True)
path.write_bytes(gzip.compress(page.encode(), compresslevel=9, mtime=0))
