[package]
name        = "org.kernel.libtracefs-static"
description = "libtracefs static library"
license     = "LGPL-2.1-only"

[provides]

[dependencies]
"org.kernel.libtracefs-devel" = "= {{release}}"
"org.kernel.libtraceevent-static" = ">= 1.9.0-1, < 2"

[files]
"@source:LICENSES/LGPL-2.1" = "usr/share/licenses/org.kernel.libtracefs-static/LGPL-2.1"
":usr/lib/x86_64-linux-peios/libtracefs.a" = "usr/lib/x86_64-linux-peios/libtracefs.a"
