[package]
name        = "com.facebook.zstd-devel"
description = "Zstandard complete shared/static development SDK"
license     = "MIT AND (BSD-3-Clause OR GPL-2.0-only)"

[provides]

[replaces]

[dependencies]
"com.facebook.zstd-libs" = "= {{release}}"

[files]
"@source:LICENSE"                                  = "usr/share/licenses/com.facebook.zstd-devel/LICENSE"
":usr/include/**"                                 = "usr/include"
":usr/lib/x86_64-linux-peios/libzstd.so"           = "usr/lib/x86_64-linux-peios/libzstd.so"
":usr/lib/x86_64-linux-peios/pkgconfig/libzstd.pc" = "usr/lib/x86_64-linux-peios/pkgconfig/libzstd.pc"
":usr/lib/x86_64-linux-peios/cmake/zstd/**"        = "usr/lib/x86_64-linux-peios/cmake/zstd"
":usr/lib/x86_64-linux-peios/libzstd.a" = "usr/lib/x86_64-linux-peios/libzstd.a"
"@source:lib/dictBuilder/divsufsort.c" = "usr/share/licenses/com.facebook.zstd-devel/LICENSE.divsufsort"
