[package]
name        = "org.sourceware.debugedit-debugsource"
description = "Debugedit debug sources"

[dependencies]
"org.sourceware.debugedit-debuginfo" = "= {{release}}"

[files]
"@source:COPYING*" = "usr/share/licenses/org.sourceware.debugedit-debugsource/"
":usr/src/debug/**" = "usr/src/debug"
