[package]
name        = "org.sourceware.debugedit-debuginfo"
description = "Debugedit debugging symbols"

[dependencies]
"org.sourceware.debugedit" = "{{version}}-1"

[files]
"@source:COPYING*" = "usr/share/licenses/org.sourceware.debugedit-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
