#!/usr/bin/env python3
"""Write packages.pekit/firmware-<family>.package.pekit.toml from families.toml.

Usage: gen-members.py [--out DIR] [--check]

Each member globs its family's tree out of the build stage. The files are
generated rather than hand-written so a family cannot exist in one place
and not the other: `pekit gen members` regenerates them, and the gen
target's verify_command runs this with --check as the drift gate.
"""
import argparse, os, sys, tomllib

HEADER = """# GENERATED by tools/gen-members.py from families.toml — do not edit.
# Regenerate with `pekit gen members`.
"""


def render(name, fam):
    lic_class = fam.get("license_class", "firmware")
    lines = [HEADER, "[package]",
             f'name          = "firmware-{name}"',
             f'description   = "{fam["description"]}"',
             f'license       = "{fam["license"]}"',
             f'license_class = "{lic_class}"',
             "", "[files]",
             f'":family/{name}/usr/lib/firmware/**"   = "usr/lib/firmware"',
             f'":family/{name}/usr/share/licenses/**" = "usr/share/licenses"',
             ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--families", default="families.toml")
    ap.add_argument("--out", default="packages.pekit")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    with open(args.families, "rb") as fh:
        doc = tomllib.load(fh)
    want = {f"firmware-{n}.package.pekit.toml": render(n, f) for n, f in doc["family"].items()}
    have = {f for f in os.listdir(args.out) if f.startswith("firmware-") and f.endswith(".package.pekit.toml")}
    stale = []
    for fname, text in want.items():
        path = os.path.join(args.out, fname)
        if not os.path.exists(path) or open(path).read() != text:
            stale.append(fname)
            if not args.check:
                with open(path, "w") as fh:
                    fh.write(text)
    for fname in sorted(have - set(want)):
        stale.append(fname + " (no such family)")
        if not args.check:
            os.unlink(os.path.join(args.out, fname))
    if args.check and stale:
        print("gen-members: package members are out of date with families.toml — run `pekit gen members`:",
              file=sys.stderr)
        for s in stale:
            print("  " + s, file=sys.stderr)
        sys.exit(1)
    print(f"gen-members: {len(want)} members {'in sync' if args.check else 'written'}")


if __name__ == "__main__":
    main()
