[package]
name        = "org.kernel.util-linux-debugsource"
description = "util-linux sources referenced by packaged debugging data"
license     = "GPL-2.0-or-later AND LGPL-2.1-or-later AND BSD-4-Clause-UC"

[dependencies]
"org.kernel.libblkid-debuginfo"         = "= {{release}}"
"org.kernel.util-linux-getopt-debuginfo" = "= {{release}}"

"org.kernel.util-linux-hexdump-debuginfo" = "= {{release}}"

[files]
"@source:COPYING" = "usr/share/licenses/org.kernel.util-linux-debugsource/COPYING"
"@source:libblkid/COPYING" = "usr/share/licenses/org.kernel.util-linux-debugsource/COPYING.libblkid"
":usr/src/debug/**" = "usr/src/debug"
