[package]
name = "org.kernel.kbd-debugsource"
description = "Console tools debug sources"

[dependencies]
"org.kernel.kbd-debuginfo" = "= {{release}}"

[files]
"@source:COPYING" = "usr/share/licenses/org.kernel.kbd-debugsource/COPYING"
":usr/src/debug/**" = "usr/src/debug"
"@recipe:src/COPYING.LIB" = "usr/share/licenses/org.kernel.kbd-debugsource/COPYING.LIB"
"@recipe:src/COPYING.LESSER" = "usr/share/licenses/org.kernel.kbd-debugsource/COPYING.LESSER"
