[package]
name        = "org.gnu.bash-debuginfo"
description = "GNU Bash debugging symbols"

[dependencies]
"org.gnu.bash" = "= {{release}}"

[files]
"@source:COPYING*"  = "usr/share/licenses/org.gnu.bash-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
