[package]
name        = "org.tukaani.xz-debuginfo"
description = "XZ Utils command and liblzma debugging symbols"
license     = "0BSD"

[dependencies]
"org.tukaani.xz" = "{{version}}-1"

[files]
"@source:COPYING.0BSD" = "usr/share/licenses/org.tukaani.xz-debuginfo/COPYING.0BSD"
":usr/lib/debug/**"    = "usr/lib/debug"
