# Independently installable stable shared-library ABI.

[package]
name        = "com.xxhash.xxhash-libs"
description = "xxHash runtime library"
license     = "BSD-2-Clause"

[provides]
libxxhash          = "{{version}}-1"
"libxxhash.so.0" = "{{version}}"

[dependencies]
glibc = ">= 2.43"

[files]
"@source:LICENSE" = "usr/share/licenses/com.xxhash.xxhash-libs/"
":usr/lib/x86_64-linux-peios/libxxhash.so.0"   = "usr/lib/x86_64-linux-peios/libxxhash.so.0"
":usr/lib/x86_64-linux-peios/libxxhash.so.0.*" = "usr/lib/x86_64-linux-peios"
