[package]
name        = "com.xxhash.xxhash-debuginfo"
description = "xxHash debugging symbols"
license     = "BSD-2-Clause AND GPL-2.0-or-later"

[dependencies]
"com.xxhash.xxhash"      = "{{version}}-1"
"com.xxhash.xxhash-libs" = "{{version}}-1"

[files]
"@source:LICENSE"     = "usr/share/licenses/com.xxhash.xxhash-debuginfo/"
"@source:cli/COPYING" = "usr/share/licenses/com.xxhash.xxhash-debuginfo/"
":usr/lib/debug/**"   = "usr/lib/debug"
