[package]
name        = "com.xxhash.xxhash-static"
description = "xxHash static library"
license     = "BSD-2-Clause"

[provides]
"xxhash-static" = "{{version}}-1"

[dependencies]
"com.xxhash.xxhash-devel" = "{{version}}-1"

[files]
"@source:LICENSE"                            = "usr/share/licenses/com.xxhash.xxhash-static/"
":usr/lib/x86_64-linux-peios/libxxhash.a" = "usr/lib/x86_64-linux-peios/libxxhash.a"
