[package]
name        = "org.gnu.mpfr-debugsource"
description = "GNU MPFR debug sources"

[dependencies]
"org.gnu.mpfr-debuginfo" = "{{version}}-1"

[files]
"@source:COPYING*" = "usr/share/licenses/org.gnu.mpfr-debugsource/"
":usr/src/debug/**" = "usr/src/debug"
