[package]
name        = "org.gnu.mpfr-debuginfo"
description = "GNU MPFR debugging symbols"

[dependencies]
"org.gnu.mpfr" = "= {{release}}"

[files]
"@source:COPYING*" = "usr/share/licenses/org.gnu.mpfr-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
