[package]
name        = "org.gnu.diffutils-debugsource"
description = "GNU file comparison utilities - debug sources"

[dependencies]
"org.gnu.diffutils-debuginfo" = "= {{release}}"

[files]
"@source:COPYING*" = "usr/share/licenses/org.gnu.diffutils-debugsource/"
":usr/src/debug/**" = "usr/src/debug"
