[package]
name        = "org.gnu.diffutils-debuginfo"
description = "GNU file comparison utilities - debugging symbols"

[dependencies]
"org.gnu.diffutils" = "= {{release}}"

[files]
"@source:COPYING*"  = "usr/share/licenses/org.gnu.diffutils-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
