[package]
name        = "org.capstone-engine.capstone-static"
description = "Capstone - static SDK compatibility umbrella"

[dependencies]
"org.capstone-engine.capstone-devel" = "{{version}}-1"

[files]
"@source:LICENSE.TXT"      = "usr/share/licenses/org.capstone-engine.capstone-static/"
"@source:LICENSE_LLVM.TXT" = "usr/share/licenses/org.capstone-engine.capstone-static/"
