format = "peipkg"
[package]
version = "{{version}}-1"
architecture = "x86_64"
license = "BSD-2-Clause AND BSD-3-Clause AND ISC AND Beerware"
license_class = "free"
homepage = "https://www.hadrons.org/software/libmd/"
