[package]
name = "org.tcpdump.tcpdump-debuginfo"
description = "Debugging symbols"
[dependencies]
"org.tcpdump.tcpdump" = "= {{release}}"
[files]
"@source:LICENSE" = "usr/share/licenses/org.tcpdump.tcpdump-debuginfo/LICENSE"
":usr/lib/debug/**" = "usr/lib/debug"
