[package]
name         = "org.gnu.ncurses-terminfo"
description  = "ncurses terminal capability database"
architecture = "noarch"

[provides]
"ncurses-base" = "{{version}}-2"
"ncurses-term" = "{{version}}-2"

[files]
"@source:COPYING"        = "usr/share/licenses/org.gnu.ncurses-terminfo/COPYING"
":usr/share/terminfo/**" = "usr/share/terminfo"
":usr/share/tabset/**"   = "usr/share/tabset"
