[package]
name        = "org.gnu.ncurses-debuginfo"
description = "ncurses debugging symbols"

[dependencies]
"org.gnu.ncurses"      = "{{version}}-2"
"org.gnu.ncurses-libs" = "{{version}}-2"

[files]
"@source:COPYING" = "usr/share/licenses/org.gnu.ncurses-debuginfo/COPYING"
":usr/lib/debug/**" = "usr/lib/debug"
