[package]
name        = "org.gnu.ncurses-debugsource"
description = "ncurses debug sources"

[dependencies]
"org.gnu.ncurses-debuginfo" = "{{version}}-3"

[files]
"@source:COPYING" = "usr/share/licenses/org.gnu.ncurses-debugsource/COPYING"
":usr/src/debug/**" = "usr/src/debug"
