[package]
name        = "org.gnu.mpc-debugsource"
description = "GNU MPC debug sources"

[provides]

[replaces]

[dependencies]
"org.gnu.mpc-debuginfo" = "{{version}}-1"

[files]
":usr/src/debug/**" = "usr/src/debug"
