[package]
name        = "org.gnu.mpc-debuginfo"
description = "GNU MPC debugging symbols"

[provides]

[replaces]

[dependencies]
"org.gnu.mpc" = "{{version}}-1"

[files]
"@source:COPYING*" = "usr/share/licenses/org.gnu.mpc-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
