[package]
name        = "org.gnu.mpc-debugsource"
description = "GNU MPC debug sources"

[provides]

[replaces]

[dependencies]
"org.gnu.mpc-debuginfo" = "{{version}}-1"

[files]
"@source:COPYING*" = "usr/share/licenses/org.gnu.mpc-debugsource/"
":usr/src/debug/**" = "usr/src/debug"
