[package]
name        = "org.gnu.sed-debuginfo"
description = "GNU sed debugging symbols"

[dependencies]
"org.gnu.sed" = "= {{release}}"

[files]
"@source:COPYING*" = "usr/share/licenses/org.gnu.sed-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
