side_effects = ["man-db"]

[package]
name         = "org.gnu.sed-common"
architecture = "noarch"
description  = "GNU sed translations, documentation and command manual"
license      = "GPL-3.0-or-later AND GFDL-1.3-no-invariants-or-later"

[files]
"@source:COPYING"      = "usr/share/licenses/org.gnu.sed-common/"
"@source:AUTHORS"      = "usr/share/doc/org.gnu.sed/"
"@source:BUGS"         = "usr/share/doc/org.gnu.sed/"
"@source:NEWS"         = "usr/share/doc/org.gnu.sed/"
"@source:README"       = "usr/share/doc/org.gnu.sed/"
"@source:THANKS"       = "usr/share/doc/org.gnu.sed/"
":usr/share/locale/**" = "usr/share/locale"
":usr/share/man/**"    = "usr/share/man"
