[package]
name        = "org.sourceware.elfutils-debuginfo"
description = "elfutils - debugging symbols"

[dependencies]
"org.sourceware.elfutils" = "{{version}}-1"

[files]
"@source:COPYING*" = "usr/share/licenses/org.sourceware.elfutils-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
