[package]
name        = "io.github.westes.flex-debuginfo"
description = "Flex and libfl debugging symbols"

[dependencies]
"io.github.westes.flex"      = "= {{release}}"
"io.github.westes.flex-libs" = "= {{release}}"

[files]
"@source:COPYING" = "usr/share/licenses/io.github.westes.flex-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
