[package]
name        = "se.curl.curl-debugsource"
description = "curl and libcurl debug sources"
license     = "curl AND ISC"

[dependencies]
"se.curl.curl-debuginfo"    = "{{version}}-1"
"se.curl.libcurl-debuginfo" = "{{version}}-1"

[files]
"@source:COPYING"    = "usr/share/licenses/se.curl.curl-debugsource/"
":usr/src/debug/**"  = "usr/src/debug"
