[package]
name        = "org.pcre.pcre2-debugsource"
description = "PCRE2 debug sources"

[dependencies]
"org.pcre.pcre2-debuginfo" = "= {{release}}"

[files]
"@source:LICENCE.md"         = "usr/share/licenses/org.pcre.pcre2-debugsource/"
"@source:deps/sljit/LICENSE" = "usr/share/licenses/org.pcre.pcre2-debugsource/LICENSE.sljit"
":usr/src/debug/**"          = "usr/src/debug"
