[package]
name        = "io.github.eudev-project.eudev-debugsource"
description = "eudev - source files for debugging"

[dependencies]
"io.github.eudev-project.eudev-debuginfo" = "= {{release}}"

[files]
"@source:COPYING" = "usr/share/licenses/io.github.eudev-project.eudev-debugsource/"
":usr/src/debug/**" = "usr/src/debug"
