[package]
name        = "io.github.eudev-project.eudev-debugsource"
description = "eudev - source files for debugging"

[dependencies]
"io.github.eudev-project.eudev-debuginfo" = "{{version}}-1"

[files]
":usr/src/debug/**" = "usr/src/debug"
