[package]
name        = "cz.ucw.pciutils-debuginfo"
description = "pciutils and libpci debugging symbols"

[dependencies]
"cz.ucw.pciutils" = "= {{release}}"
"cz.ucw.libpci"   = "= {{release}}"

[files]
"@source:COPYING" = "usr/share/licenses/cz.ucw.pciutils-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
