[package]
name        = "org.gnu.gawk-debuginfo"
description = "GNU Awk interpreter, helper and extension debugging symbols"

[dependencies]
"org.gnu.gawk" = "= {{release}}"

[files]
"@source:COPYING" = "usr/share/licenses/org.gnu.gawk-debuginfo/"
":usr/lib/debug/**" = "usr/lib/debug"
