[package]
name        = "org.sourceware.bzip2-debugsource"
description = "bzip2 - debug sources"

[dependencies]
"org.sourceware.bzip2-debuginfo" = "= {{release}}"

[files]
"@source:LICENSE" = "usr/share/licenses/org.sourceware.bzip2-debugsource/LICENSE"
":usr/src/debug/**" = "usr/src/debug"
